#!/usr/bin/with-contenv sh

SECRET="/var/lib/samba/private/secrets.tdb"

if [ -f "${SAMBA_CONFIG}" ]; then
    echo "INFO: found samba config in ${SAMBA_CONFIG}"
else
    echo "ERROR: samba config not found in ${SAMBA_CONFIG}"
    exit 1
fi

if [ -f "${NSLCD_CONFIG}" ]; then
    echo "INFO: found nslcd config in ${NSLCD_CONFIG}"
else
    echo "ERROR: nslcd config not found in ${NSLCD_CONFIG}"
    exit 1
fi

if [ ! -e $SECRET ]]; then
    echo "INFO: $SECRET does not exists, creating one"
    exit 15

    if [ -z "${SAMBA_LDAP_PASSWORD}" ]; then
        echo "ERROR: Environment variable SAMBA_LDAP_PASSWORD not set"
        exit 17
    else
        smbpasswd -w $SAMBA_LDAP_PASSWORD
    fi
    if [ ! -e $SECRET ]]; then
        echo "ERROR: $SECRET does not exists"
        exit 15
    fi
fi

if [ ! -z "${SID}" ]; then
    net setlocalsid "${SID}"
fi
